# Generated by Django 3.0.5 on 2020-04-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderitems',
            new_name='items',
        ),
    ]
