# Generated by Django 3.0.5 on 2020-04-17 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200417_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='item.OrderItem'),
        ),
    ]
