# Generated by Django 3.0.4 on 2020-03-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
