# Generated by Django 3.0.4 on 2020-03-25 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20200325_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='inv_count',
            field=models.PositiveIntegerField(verbose_name=django.core.validators.MinValueValidator(1)),
        ),
    ]
