# Generated by Django 3.0.4 on 2020-03-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20200325_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='buyer',
        ),
        migrations.AlterField(
            model_name='item',
            name='inv_count',
            field=models.PositiveIntegerField(),
        ),
    ]
