# Generated by Django 3.0.4 on 2020-03-26 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20200325_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='buyer',
        ),
    ]
