# Generated by Django 3.0.5 on 2020-04-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_auto_20200408_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.CharField(default='fakeemail@default.ca', max_length=100),
            preserve_default=False,
        ),
    ]
